# Generated by Django 5.2 on 2025-05-27 21:04

import bookings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', 'create_order'),
        ('facilities', '0009_amenity_name_ru_amenity_name_uz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paycom_transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='Уникальный идентификатор транзакции, присвоенный Paycom.', max_length=50, null=True, unique=True, verbose_name='ID транзакции Paycom'),
        ),
        migrations.AddField(
            model_name='order',
            name='paycom_transaction_state',
            field=models.IntegerField(blank=True, choices=[(1, 'Создана'), (2, 'Завершена'), (-1, 'Отменена до проведения'), (-2, 'Отменена после проведения')], help_text='1: Создана, 2: Завершена, -1: Отменена (до проведения), -2: Отменена (после проведения)', null=True, verbose_name='Состояние транзакции Paycom'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_transaction_link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_order_link', to='bookings.paymenttransaction', verbose_name='Связанная внутренняя платежная транзакция'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='expires_at',
            field=models.DateTimeField(default=bookings.models.default_payment_transaction_expires_at, verbose_name='Сессия ПС истекает в'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='item_parameters',
            field=models.JSONField(help_text='Содержит facility_id, даты, слоты, дни, цену и т.д.', verbose_name='Параметры заказа на момент создания сессии'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('intent_created', 'Платежный интент создан'), ('processing_stripe', 'Обработка платежной системой'), ('succeeded_stripe', 'Успешно оплачено (ПС)'), ('failed_stripe', 'Ошибка оплаты (ПС)'), ('expired_stripe_session', 'Истекло время сессии ПС'), ('order_creation_pending', 'Ожидание создания заказа'), ('order_created_successfully', 'Заказ успешно создан'), ('order_creation_failed', 'Ошибка создания заказа (после оплаты)'), ('refund_processing_pt', 'Обработка возврата'), ('refunded_pt', 'Возвращено')], db_index=True, default='intent_created', max_length=30, verbose_name='Статус транзакции'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['paycom_transaction_id'], name='bookings_or_paycom__5f6c32_idx'),
        ),
    ]
