# Generated by Django 5.2 on 2025-05-27 21:54

import bookings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_order_paycom_transaction_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='bookings_or_paycom__5f6c32_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paycom_transaction_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paycom_transaction_state',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='paycom_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='ID транзакции в Paycom'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='paycom_state',
            field=models.IntegerField(blank=True, help_text='1: создана, 2: завершена, -1: отменена, -2: отменена после завершения', null=True, verbose_name='Состояние транзакции в Paycom'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='paycom_time_created_ms',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Время создания транзакции в Paycom (мс)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_transaction_link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_order', to='bookings.paymenttransaction', verbose_name='Связанная платежная транзакция'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=bookings.models.default_payment_transaction_expires_at, null=True, verbose_name='Сессия/Намерение истекает в'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='item_parameters',
            field=models.JSONField(help_text='Содержит facility_id, даты, слоты, дни, цену и т.д.', verbose_name='Параметры заказа на момент создания сессии оплаты'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('intent_created', 'Stripe сессия создана'), ('awaiting_paycom_redirect', 'Paycom: Ожидание перехода к оплате'), ('processing_stripe', 'Stripe: Обработка'), ('paycom_processing', 'Paycom: Обработка'), ('succeeded_stripe', 'Stripe: Успешно оплачено'), ('failed_stripe', 'Stripe: Ошибка оплаты'), ('failed_paycom', 'Paycom: Ошибка/Отмена оплаты'), ('expired_stripe_session', 'Stripe: Истекло время сессии'), ('order_creation_pending', 'Ожидание создания заказа'), ('order_created_successfully', 'Заказ успешно создан'), ('order_creation_failed', 'Ошибка создания заказа (после оплаты)'), ('refund_processing_pt', 'Обработка возврата'), ('refunded_pt', 'Возвращено')], db_index=True, default='awaiting_paycom_redirect', max_length=30, verbose_name='Статус транзакции'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['paycom_id'], name='bookings_pa_paycom__a3870c_idx'),
        ),
    ]
