# Generated by Django 5.2 on 2025-05-28 16:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_order_status_alter_paymenttransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Если транзакция не будет оплачена до этого времени, она может быть автоматически отменена системой.', null=True, verbose_name='Время истечения (для неоплаченных)'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='item_parameters',
            field=models.JSONField(help_text='Содержит facility_id, даты, слоты, дни, цену и т.д. для сверки.', verbose_name='Параметры заказа на момент инициации оплаты'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='item_type_at_creation',
            field=models.CharField(choices=[('entry_fee', 'Оплата за вход'), ('slot_booking', 'Слотовое бронирование'), ('subscription', 'Подписка/Абонемент')], db_index=True, help_text='Тип заказа, для которого создавалась эта транзакция', max_length=20, verbose_name='Тип заказа при создании'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='paycom_id',
            field=models.CharField(blank=True, db_index=True, help_text='Уникальный идентификатор транзакции от Paycom (из CreateTransaction).', max_length=255, null=True, unique=True, verbose_name='ID транзакции в Paycom'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='paycom_state',
            field=models.IntegerField(blank=True, help_text='1: создана, 2: завершена, -1: отменена до проведения, -2: отменена после проведения.', null=True, verbose_name='Состояние транзакции в Paycom'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='paycom_time_created_ms',
            field=models.BigIntegerField(blank=True, help_text='Timestamp от Paycom из метода CreateTransaction (params.time).', null=True, verbose_name='Время создания транзакции в Paycom (мс)'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('awaiting_provider_redirect', 'Ожидание перехода к оплате'), ('provider_processing', 'Обработка платежным провайдером'), ('provider_payment_failed', 'Ошибка/Отмена оплаты (у провайдера)'), ('provider_expired', 'Истек срок оплаты (у провайдера)'), ('order_confirmed_by_provider', 'Заказ успешно оплачен и подтвержден'), ('order_confirmation_failed', 'Ошибка подтверждения заказа (требуется возврат)'), ('refund_processing', 'Обработка возврата'), ('refunded', 'Возвращено')], db_index=True, default='awaiting_provider_redirect', max_length=35, verbose_name='Статус транзакции'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='stripe_charge_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Stripe Charge ID (архив)'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Stripe Payment Intent ID (архив)'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='stripe_refund_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Stripe Refund ID (архив)'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='stripe_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Stripe Session ID (архив)'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Внутренней Транзакции'),
        ),
    ]
