# Generated by Django 4.2.18 on 2025-04-05 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='working_hours',
            field=models.CharField(blank=True, default='Пн-Сб: 8:00 - 20:00', max_length=100, null=True, verbose_name='Часы работы (общие)'),
        ),
        migrations.CreateModel(
            name='UniversityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='university_gallery/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='universities.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Галерея университета',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=150, verbose_name='Должность')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, verbose_name='Краткая биография')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='universities.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Сотрудник спорт. отдела',
                'verbose_name_plural': 'Сотрудники спорт. отдела',
                'ordering': ['university', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='SportClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название кружка')),
                ('sport_type', models.CharField(max_length=100, verbose_name='Вид спорта')),
                ('icon_class', models.CharField(blank=True, help_text="Например, 'fas fa-futbol'", max_length=50, verbose_name='Класс иконки FontAwesome')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('schedule_info', models.TextField(blank=True, help_text='Пример: Пн, Ср, Пт: 18:00 - 20:00', verbose_name='Информация о расписании')),
                ('coach_name_manual', models.CharField(blank=True, help_text='Используйте, если тренера нет в списке персонала', max_length=255, verbose_name='Тренер (текст)')),
                ('contact_info', models.CharField(blank=True, max_length=200, verbose_name='Контактная информация')),
                ('image', models.ImageField(blank=True, null=True, upload_to='club_images/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.staff', verbose_name='Тренер (из персонала)')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_clubs', to='universities.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Спортивный кружок',
                'verbose_name_plural': 'Спортивные кружки',
                'ordering': ['university', 'name'],
            },
        ),
    ]
