# Generated by Django 4.2.18 on 2025-04-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_working_hours_universityimage_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityimage',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Изображение галереи', 'verbose_name_plural': 'Галерея университета'},
        ),
        migrations.AddField(
            model_name='university',
            name='campus_image',
            field=models.ImageField(blank=True, help_text='Горизонтальное изображение для карточки и шапки страницы университета.', null=True, upload_to='university_campus/', verbose_name='Фоновое изображение (кампус)'),
        ),
        migrations.AlterField(
            model_name='sportclub',
            name='contact_info',
            field=models.CharField(blank=True, max_length=200, verbose_name='Контактная информация (тел/email)'),
        ),
        migrations.AlterField(
            model_name='sportclub',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='sportclub',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='sportclub',
            name='schedule_info',
            field=models.TextField(blank=True, help_text='Пример: Пн, Ср, Пт: 18:00 - 20:00, Спортзал А', verbose_name='Информация о расписании'),
        ),
        migrations.AlterField(
            model_name='sportclub',
            name='sport_type',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Вид спорта'),
        ),
        migrations.AlterField(
            model_name='sportclub',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='university',
            name='city',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='university',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='university',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Отображается ли университет на платформе и доступны ли его объекты.', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, help_text='Рекомендуется квадратное изображение для лучшего отображения.', null=True, upload_to='university_logos/', verbose_name='Логотип (квадратный)'),
        ),
        migrations.AlterField(
            model_name='university',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='universityimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
    ]
