# Generated by Django 5.2 on 2025-05-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_sportclub_coach_name_manual_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='payme_merchant_id',
            field=models.CharField(blank=True, help_text="ID кассы университета в Payme Business. Используется как 'логин' для Basic Auth от Payme и как 'm' параметр ссылки.", max_length=255, null=True, verbose_name='Payme Merchant ID (Касса ID)'),
        ),
        migrations.AddField(
            model_name='university',
            name='payme_secret_key_production',
            field=models.CharField(blank=True, help_text="Боевой ключ кассы из Payme Business. Используется как 'пароль' для Basic Auth от Payme.", max_length=255, null=True, verbose_name='Payme Secret Key (Боевой)'),
        ),
        migrations.AddField(
            model_name='university',
            name='payme_secret_key_test',
            field=models.CharField(blank=True, help_text="Тестовый ключ кассы из Payme Business (для sandbox или test). Используется как 'пароль' для Basic Auth от Payme.", max_length=255, null=True, verbose_name='Payme Secret Key (Тестовый)'),
        ),
    ]
