# Generated by Django 5.2 on 2025-05-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_university_payme_merchant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='payme_merchant_id',
            field=models.CharField(blank=True, help_text="ID кассы университета в Payme Business. Указывается в поле 'merchant' при формировании чека.", max_length=255, null=True, verbose_name='Payme Merchant ID (Касса ID)'),
        ),
        migrations.AlterField(
            model_name='university',
            name='payme_secret_key_production',
            field=models.CharField(blank=True, help_text='Боевой ключ кассы из Payme Business. Используется для Basic Auth от Payme к нам.', max_length=255, null=True, verbose_name='Payme Secret Key (Боевой)'),
        ),
        migrations.AlterField(
            model_name='university',
            name='payme_secret_key_test',
            field=models.CharField(blank=True, help_text='Тестовый ключ кассы из Payme Business (для sandbox.paycom.uz). Используется для Basic Auth от Payme к нам.', max_length=255, null=True, verbose_name='Payme Secret Key (Тестовый Sandbox)'),
        ),
    ]
