# Generated by Django 4.2.18 on 2025-03-31 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название удобства')),
                ('icon_class', models.CharField(blank=True, help_text="Например, 'fas fa-shower'", max_length=50, verbose_name='Класс иконки FontAwesome')),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'Удобства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название объекта')),
                ('facility_type', models.CharField(choices=[('football', 'Футбольное поле'), ('basketball', 'Баскетбольная площадка'), ('tennis', 'Теннисный корт'), ('volleyball', 'Волейбольная площадка'), ('swimming', 'Бассейн'), ('gym', 'Тренажерный зал'), ('other', 'Другое')], max_length=50, verbose_name='Тип объекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price_per_hour', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена за час (сум)')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='Размеры/Площадь')),
                ('location_details', models.CharField(blank=True, help_text="Например, 'Корпус Б, 2 этаж'", max_length=255, verbose_name='Детали расположения')),
                ('open_time', models.TimeField(verbose_name='Время открытия')),
                ('close_time', models.TimeField(verbose_name='Время закрытия')),
                ('working_days', models.CharField(default='Пн,Вт,Ср,Чт,Пт,Сб', help_text='Перечислите дни через запятую, например: Пн,Вт,Ср,Чт,Пт', max_length=100, verbose_name='Рабочие дни')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Контактный телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен для бронирования')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='facility_images/', verbose_name='Главное изображение')),
                ('amenities', models.ManyToManyField(blank=True, to='facilities.amenity', verbose_name='Удобства')),
                ('responsible_person', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_facilities', to=settings.AUTH_USER_MODEL, verbose_name='Ответственное лицо')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='universities.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Спортивный объект',
                'verbose_name_plural': 'Спортивные объекты',
                'ordering': ['university', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FacilityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='facility_images/', verbose_name='Изображение')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='facilities.facility', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Изображение объекта',
                'verbose_name_plural': 'Изображения объектов',
            },
        ),
    ]
