# Generated by Django 4.2.18 on 2025-04-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilityimage',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'Изображение объекта', 'verbose_name_plural': 'Изображения объектов'},
        ),
        migrations.AddField(
            model_name='facilityimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='icon_class',
            field=models.CharField(blank=True, help_text="Например, 'fas fa-shower' или 'fa-solid fa-wifi'", max_length=50, verbose_name='Класс иконки FontAwesome'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Контактный телефон объекта'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы временно скрыть объект из каталога и запретить бронирование.', verbose_name='Доступен для бронирования'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='location_details',
            field=models.CharField(blank=True, help_text="Например, 'Спорткомплекс, Корпус Б, 2 этаж'", max_length=255, verbose_name='Детали расположения'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='working_days',
            field=models.CharField(default='Пн,Вт,Ср,Чт,Пт,Сб', help_text='Перечислите сокращенные названия дней через запятую (Пн, Вт, Ср, Чт, Пт, Сб, Вс)', max_length=100, verbose_name='Рабочие дни'),
        ),
        migrations.AlterField(
            model_name='facilityimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
    ]
