# Generated by Django 4.2.18 on 2025-05-08 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_facility_booking_type_facility_max_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='booking_type',
            field=models.CharField(choices=[('exclusive_slot', 'Эксклюзивный слот (1 бронь на время)'), ('overlapping_slot', 'Пересекающийся слот (несколько броней, нужна вместимость)'), ('entry_fee', 'Оплата за вход (без временных слотов)')], default='exclusive_slot', help_text='Определяет, как пользователи могут бронировать этот объект.', max_length=20, verbose_name='Тип бронирования'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='max_capacity',
            field=models.PositiveIntegerField(blank=True, help_text="Укажите максимальное количество одновременных броней для одного временного слота (только для типа 'Пересекающийся слот').", null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Макс. вместимость слота'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=0, help_text="Цена за 1 час для почасового бронирования или цена за вход для типа 'Оплата за вход'.", max_digits=10, verbose_name='Цена за час/вход (сум)'),
        ),
    ]
