# Generated by Django 5.2 on 2025-05-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_alter_facility_booking_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='max_capacity',
        ),
        migrations.AddField(
            model_name='facility',
            name='allow_entry_fee_subscriptions',
            field=models.BooleanField(default=False, help_text="Применимо только для объектов с типом доступа 'Оплата за вход'. Позволяет пользователям покупать абонементы на многократные посещения в указанные дни недели.", verbose_name='Разрешить подписки на вход?'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='booking_type',
            field=models.CharField(choices=[('exclusive_slot', 'Эксклюзивный слот (1 бронь на время)'), ('entry_fee', 'Оплата за вход (без временных слотов)')], default='exclusive_slot', help_text='Определяет, как пользователи могут взаимодействовать с объектом.', max_length=20, verbose_name='Тип бронирования/доступа'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы временно скрыть объект из каталога.', verbose_name='Доступен для бронирования/посещения'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=0, help_text="Цена за 1 час для 'Эксклюзивного слота' ИЛИ цена за разовый вход для 'Оплаты за вход'.", max_digits=10, verbose_name='Цена за час / за вход (сум)'),
        ),
    ]
