# Generated by Django 4.2.18 on 2025-05-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_remove_facility_allow_entry_fee_subscriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='working_days',
            field=models.CharField(default='0,1,2,3,4,5', help_text='Числа дней недели через запятую (Пн=0, Вт=1, ..., Вс=6).', max_length=20, verbose_name='Рабочие дни'),
        ),
    ]
