# Generated by Django 4.2.18 on 2025-05-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0008_convert_working_days_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название удобства'),
        ),
        migrations.AddField(
            model_name='amenity',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название удобства'),
        ),
        migrations.AddField(
            model_name='facility',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='facility',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='facility',
            name='location_details_ru',
            field=models.CharField(blank=True, help_text="Например, 'Спорткомплекс, Корпус Б, 2 этаж'", max_length=255, null=True, verbose_name='Детали расположения'),
        ),
        migrations.AddField(
            model_name='facility',
            name='location_details_uz',
            field=models.CharField(blank=True, help_text="Например, 'Спорткомплекс, Корпус Б, 2 этаж'", max_length=255, null=True, verbose_name='Детали расположения'),
        ),
        migrations.AddField(
            model_name='facility',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название объекта'),
        ),
        migrations.AddField(
            model_name='facility',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Название объекта'),
        ),
        migrations.AddField(
            model_name='facility',
            name='size_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Размеры/Площадь'),
        ),
        migrations.AddField(
            model_name='facility',
            name='size_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Размеры/Площадь'),
        ),
    ]
