# Generated by Django 4.2.18 on 2025-05-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_managers_remove_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Not used for login. Required by Django for admin/superuser compatibility.', max_length=150, verbose_name='username'),
        ),
    ]
